# Generated by Django 4.2.2 on 2023-06-30 16:06

import core.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='picture',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=1048, upload_to=core.models.getFilename),
        ),
    ]
