# Generated by Django 4.2.2 on 2023-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
    ]
